server:
  port: 8086
spring:
  main:
    allow-bean-definition-overriding: true
# 多个选项用空格隔开
userConfig:
  # 超级管理员，建议只给自己
  administrators: ''
  # Bot名称，只响应以Bot名开头的消息
  botNames: '测试'
  # QQ账号密码列表
  qqList: ''
  pwList: ''

  # 登录协议，可选项有：IPAD ANDROID_PAD ANDROID_PHONE MACOS，推荐IPAD或MACOS
  typeList: 'IPAD'

  # QQ频道机器人登录信息
  token: ''
  appId: ''
  type: ''