server:
  port: 8086
  tomcat:
    #最大链接数
    max-connections: 1500
    #最大等待队列长度
    accept-count: 1000
    threads:
      min-spare: 4
      max: 10
spring:
  main:
    allow-bean-definition-overriding: true
# 多个选项用空格隔开
userConfig:
  agree: true
  # 超级管理员，建议只给自己
  administrators: '412459523'
  # Bot名称，只响应以Bot名开头的消息
  botNames: '测试'
  # QQ账号密码列表
  qqList: ''
  pwList: ''

  # 登录协议，可选项有：IPAD ANDROID_PAD ANDROID_PHONE MACOS，推荐IPAD或MACOS
  typeList: 'IPAD'

# QQ频道机器人登录信息
  # BotAPPID 开发者ID
  appId: ''
  # 机器人令牌
  token: ''
  # 公域还是私域 public/private
  type: ''